# Site settings
title:          Alex Le
description:    "Alex Le lives in Colorado and is a software engineer. He likes to run, read, and tinker with technology and side projects."
tagline:        "Software Engineer, Minimalist, Improving Runner"
url:            "https://alexanderle.com"
production_url: "https://alexanderle.com"

# Google Analytics (GA4)
google_analytics: G-S03KNPH8PC

# Author
author:
  name:         Alex Le
  url:          https://alexanderle.com
  email:        alex.csm@gmail.com
  github:       alexle
  twitter:      alextrle

# Build settings
markdown:       kramdown
include:
  - _pages

# Preserves optimized images between builds
keep_files:     [assets/images]

# Only rebuild changed files
incremental:    true

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-archives
  - jemoji

# Jekyll Feed Configuration
feed:
  excerpt_only: true

# Permalinks
permalink:      /:title
paginate:       7

# Social
twitter_username:     alextrle
github_username:      alexle
linkedin_username:    alexle
instagram_username:   alextrle
feed_xml:             feed.xml

# Excludes
exclude:        [Gemfile, Gemfile.lock, tale.gemspec, vendor, node_modules]
